micronaut:
  application:
    name: feed-reader
  server:
    port: 1234
    context-path: /hbr/feed
    netty:
      max-header-size: 16384 # in bytes
      worker:
        event-loop-group: worker
  executors:
    io:
      type: work_stealing
      n-threads: 75
    scheduled:
      type: scheduled
      core-pool-size: 50
  netty:
    event-loops:
      default:
        num-threads: 10
      worker:
        num-threads: 10
      httpclient:
        num-threads: 10
  http:
    client:
      read-timeout: 15s
      event-loop-group: httpclient
    services:
      hbr:
        url: https://hbr.org
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  jackson:
    serializationInclusion: ALWAYS
  endpoints:
    info:
      enabled: true
      sensitive: false
    health:
      enabled: true
      sensitive: false
    routes:
      enabled: true
      sensitive: false
